### PR TITLE
Adding more pride to PRs

### PR DESCRIPTION
**Pull request by hx-markterry**
I've updated the gif wording, in the hope to generate a more positive mindset around the creation of a PR. I see the completion of the template the final touches to some awesome code rather than just a formality. Hope this gets across to everyone.
- [x] hey, I kinda like this
- [x] I'm with the other guy

### CODE REVIEW

**Comment by connormeredith** [comment]
hey, I kinda like this :+1:

**Comment by rahulpatel** [comment]
I'm with the other guy :+1:

**Comment by jodiedoubleday** [comment]
:-1: not sure there is much point to this. I don't think it would change mindset. What if i don't like cherries or cakes? ( I :heart: :cake:)

**Comment by joestump** [comment]
I prefer the reaction GIF. It helps me get into the mindset of the person who did the work and builds empathy (for me anyways).

**Comment by shackpank** [comment]
:-1: to this, and in general to static creative headings in templates we see many times every day. It'll get [annoying](http://knowyourmeme.com/memes/patrolling-the-mojave) in short order unless we [put effort into keeping them fresh](https://github.com/npm/npm-expansions)

**Pull request closed without merging**
