### PR TITLE
Client-side Dependencies

### PR DESCRIPTION
**Pull request by elliotstokes**

### CODE REVIEW

**Comment by connormeredith** [comment]
If this relates only to clientside dependencies it might be worth renaming the file to reflect that, or adding it as the heading :)

**Comment by dancork** [comment]
Despite not bundling the JS it could have performance impacts serverside too.

**Comment by dancork** [comment]
Looks good to me, might be worth adding something about choosing modules carefully too. Eg Not bloated with stuff we don't need, regularly maintained, yada yada.

**Comment by hx-markterry** [comment]
The content here is good, but I think we should move it under this heading: https://github.com/holidayextras/culture/blob/master/general-javascript-best-practices.md#dependencies

**Comment by elliotstokes** [comment]
That sounds like a good idea - ill move it now.

**Comment by hx-markterry** [comment]
OK with me

**Pull request merged**
