### PR TITLE
Fixes broken links in the README

### PR DESCRIPTION
**Pull request by cameronviner**
Seems the links in the read me have become broken when this was moved over, this just points them to the correct place.

### CODE REVIEW

**Comment by lukefrake** [comment]
Good shout, my mistake.

I've made the same changes in another file and pushed into here as well.

**Comment by hxpaul** [comment]
could these be made relative links?

**Comment by cameronviner** [comment]
@hxpaul Yep have just made that change could you have another look when you get a second

**Comment by hxpaul** [comment]
:+1:

**Comment by pmcnr-hx** [comment]
I would remove the redundant preceding `/` from the file names in the links for these to actually be relative to `README.md`.

**Comment by hpoom** [comment]
Merged as people are commenting on broken links.

@pmcnr-hx If you think it still need changing do another PR

**Comment by pmcnr-hx** [comment]
Agreed @hpoom: it's merely cosmetic. It can always be improved in the context of a future PR.

**Pull request merged**
