### PR TITLE
Migrate docs over from shortbreaks github

### PR DESCRIPTION
**Pull request by philmeehan**
#### What does this PR do? (please provide any background)

We're shutting down the Shortbreaks Github account.

We had a 'culture' repo there. These are the docs that we want to keep at the moment. The PR template will kept longer term but the 'guidelines' repos are going to be looked at merging in longer term.

Nicki Lever and Dave Hersey are going to lead on bringing them up to Group standard and moving them out of this directory.

_HX_ 
- [x] :+1:

_Shortbreaks_
- [x] :+1: @kevinhodges

### CODE REVIEW

**Comment by hx-markterry** [comment]
OK with me, but could you also update the readme's table of contents to link to the new files, please.

**Comment by hx-markterry** [comment]
Apart from the PR templates, I think the other files can go straight in the root of the repo as we have no conflicting docs in distribution, these can then be the basis of any best practices moving forward.

**Comment by philmeehan** [comment]
@hx-markterry that was my initial thought but I didn't feel it was my place to argue for or against HTML/CSS practices.

**Comment by philmeehan** [comment]
Have now linked the docs from the main README and moved the best practices into the root.

**Comment by kevinhodges** [comment]
I'm now ok with the PR :+1:

**Comment by hx-markterry** [comment]
ok with me :rooster:

**Comment by philmeehan** [comment]
Thanks guys :)

**Pull request merged**
