### PR TITLE
pr-template-ip added IP slot in template

### PR DESCRIPTION
**Pull request by Arditc**
# What does this change?

Added IP slot in the Pr-template
# Why?

We would like to allow IP's to be have a slot so that they'll be able to review PR's. This is an optional field which means if you don't get an IP to review the PR it won't block you from pushing your work forward.

### CODE REVIEW

**Comment by hxpaul** [comment]
I don't think this needs another checkbox - do feel free to review prs, but I don't think we need any optional checkboxes. We previously had dozens of checkboxes, some were optional, I don't think it added anything. Sorry.

**Comment by dancork** [comment]
If anything we need less checkboxes, not more. I don't believe these are needed for IPs to give a review and comment on a PR.

**Comment by michaelcarter** [comment]
IPs are being allowed to +1 again (explanation in this week's group tech update due to be sent shortly...). The slot is optional and designed not to hold up work from going to production, but it does give IPs the opportunity to get involved in the code review process as part of their learning/development objectives.

Without that context this PR is probably a little confusing, sorry!

**Comment by dancork** [comment]
@michaelcarter but does it require tick boxes? when i look down the list of PRs to review I look for `X of 9` as to whether a slots available. this could be misleading as `9 of 13` could be needing a review and it could be ready to ship.

**Comment by ghost** [comment]
I just wanted to clarify the process for the not new but Different third tick box for the IP's. We want the IP's to take part in code reviews and having a tick box encourages this and gives them some ownership with regards to the comments and questions they ask on a PR. 

However we have learnt from experience and want to make the additional tick box OPTIONAL. An open PR does not require an IP to have reviewed the code, which is different to our old process. However if they do take part in the review there feedback and comments should be treated with the same weight as any other member of the team.

**Comment by ghost** [comment]
@dancork the tick boxes will help the IP's to demonstrate their efforts for personal development, they can  demonstrate what PR's they have taken part in to help with PD discussions, it will also avoid situations where more than one IP review a PR.

**Comment by Joezo** [comment]
@dancork I had the same concern but I think it can be addressed by ensuring that we use labels correctly. I think it's good to include everyone, who wants to be, in the code review process.

**Comment by tompricetech** [comment]
Not a big fan of having more checkboxes. Plus if they are optional it will be hard to see at a glance which PRs have already been reviewed looking at the list http://grab.by/LVLo. One ticket could have 9/13 and be ready to go and another could have the same but still need a non IP review.

**Comment by pmcnr-hx** [comment]
If we put DevD's PR distributor in production, we should be able to have statistics of all the PRs any developer, including IPs, have participated in. Shall we focus on finishing this work on the next project lounge? I'll be happy to coordinate (since I've already volunteered for the role previously but have not really been pushing the project forward) if this is a solution that will satisfy everyone.

**Comment by dancork** [comment]
Happy to go with the consensus. Personally, I feel we need less tick boxes not more. I'd love to see a situation where we removed all tick boxes and the PR template said...

```
By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the authors machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.
```

I'm not sure ticking a box demonstrates effort for PD. Commenting is a much more effective method for showing understanding or questioning when there is a lack thereof. Removal of tick boxes would probably encourage more commenting too, I see a lot of PRs with 9 ticks and 2 :+1:s which to me seems to offer little value or feedback to the author.

**Comment by ghost** [comment]
That sounds like a brilliant idea @pmcnr-hx, can we until then merge this PR in then so the IP's can start to take part in our current process. 

@dancork it sounds like your ideas and feedback are around the whole PR process with regards to what a PR should look like when it is reviewed, can I suggest we move that to a new discussion. I understand your points but I think other people in the Web Team see value in the tick boxes.

Can we agree merge this is then with the caveat of:
1. When the PR distributer is up and running we can review the purpose of this and then also have a discussion on whether we can change the PR template as a whole? @hxtomprice

**Comment by hx-markterry** [comment]
@Arditc as this is a culture change could you get some feedback from short breaks devs too, as per the docs thanks.

**Comment by dancork** [comment]
@christinamattinson I see your point, however I feel my comments are relevant as we're discussing the need for tick boxes.

I'm not sure I agree that the web team see value in the tick boxes as a whole, 4 people on this PR have implied that they'd like to see less tick boxes not more. I see a lot of devs not tick anything and then when they :+1: they tick all 4, as a formality.

For the IPs personal development I believe it would be better for them to comment and add their +1, it would demonstrate a greater understanding of the work they're reviewing. It would also help us as peers to give more constructive feedback, with tick boxes I'm not sure I can give salient feedback.

**Comment by philmeehan** [comment]
We currently use a different template in Shortbreaks, and we don't have IPs at the moment so this won't affect us at the moment.

I find the checkboxes useful personally for reminding us on things that we have to check in the PR. If I am acting as a QA on the Jira the checkboxes allow me to see at a glance that enough required people have approved the PR, instead of having to scroll through the comments.

**Comment by hxpaul** [comment]
This change would stop that happening wouldn't it @philmeehan ? you'd see a pr had 9 / 13 boxes ticked but not know if enough required people had approved it.

**Comment by philmeehan** [comment]
@hxpaul We normally link directly to the PRs that have to be merged by the QA inside a comment on the relevant Jira, and you would normally only be looking at the checkboxes labelled '+1 from me'.

**Comment by dancork** [comment]
Created a PR for an alternative suggestion... https://github.com/holidayextras/culture/pull/68

**Comment by michaelcarter** [comment]
People seem to have a lot of opinions on this, but generally agree with Dan's proposed changes in his PR (https://github.com/holidayextras/culture/pull/68) . In order to avoid a never ending back and forth I've merged Dan's PR, so am closing this one now.

**Pull request closed without merging**
