### PR TITLE
NightwatchJS Best Practices

### PR DESCRIPTION
**Pull request by cameronviner**
#### What does this PR do? (please provide any background)

Start of a document that explains the best practices we use/adhere to when writing NightwatchJS tests
#### What gif best describes how you feel about this work?

---
- [x] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.
#### Reviewers

**Review 1**
- [ ] :+1:

**Review 2**
- [ ] :+1:

**Review 3**
- [ ] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

### CODE REVIEW

**Comment by tompricetech** [comment]
Spoiler alert

**Comment by jamieb345** [comment]
👍

**Comment by JackMoggy** [comment]
👍

**Comment by hxmattobee** [comment]
Good start I reckon 👍

**Pull request merged**
