### PR TITLE
Update tickbox order

### PR DESCRIPTION
**Pull request by hx-markterry**
# Whats this change

Change the order of the acceptance tick boxes.
# Why?

I always find myself ticking some later tick boxes first, so I thought I'd stick a PR in and see if others agree. The reordered way reflects how far I/others are through the review process.
- [x] One person agrees
- [x] Two people agrees
- [x] Three people agrees!

### CODE REVIEW

**Comment by hpoom** [comment]
:+1:  from me. New order appears logical.

**Comment by HeinBehrenshx** [comment]
+1

**Comment by dancork** [comment]
Should coding anti-patterns be first? Personally I check the code first, then coverage.

**Comment by hx-markterry** [comment]
@dancork this is order better or worst than the current order?

**Comment by dancork** [comment]
Definitely better!

**Comment by jamesmcneil** [comment]
:+1:

**Pull request merged**
