### PR TITLE
More links for the technical resources page

### PR DESCRIPTION
**Pull request by hx-markterry**
Please add any links of interest to this doc or in the comments of this PR whichever is easier

### CODE REVIEW

**Comment by hx-markterry** [comment]
Thanks for the additions on this PR so far, I've made some changes in order to clarify the aim of this doc.

**Comment by hpoom** [comment]
Looks good to me :+1: I do wonder it the links removed could be placed on the headers. So "Less" as a header could link to the official Less homepage, then links under. Just an idea.

I am happy for this to be merged or to merge this and we can tackle that in a later iteration.

**Comment by robhuzzey** [comment]
Can this be something shared with SB too?

**Comment by hpoom** [comment]
@robhuzzey This is shared with SB, it is in the HX culture repo which is all "HX Group" stuff.

**Comment by lukefrake** [comment]
As these don't seem in any particular order, could they be alphabetised?

**Pull request merged**
